name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 1

      - name: Download pandoc
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
            repo: jgm/pandoc
            version: tags/2.19.2
            file: pandoc-2.19.2-1-amd64.deb
            target: pandoc-2.19.2-1-amd64.deb
      - name: Install and Build
        run: |
            sudo dpkg -i pandoc-2.19.2-1-amd64.deb
            pandoc --version
            make

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: OUT
            token: ${{ secrets.LIBALLEG_FORK_TESTING }}
            branch: master
            repository-name: SiegeLord/liballeg.github.io
            commit-message: Automatic update from allegrowww2
            clean: true
            clean-exclude: |
                CNAME
                donations.html
                a5docs/4*/**
                a5docs/5*/**
                a5docs/trunk**
                docs/docs/**
                search/**
